#include "variables.h"

const int cascadaBPM = 170;
const int cascadaSize = 41;
const int cascadaBassSize = 59;

const std::pair<float, float> cascada[cascadaSize] = {
  std::make_pair(CROCHE, Gd),
  std::make_pair(CROCHE, Gd),
  std::make_pair(CROCHE, G2),
  std::make_pair(CROCHE, G2),
  std::make_pair(CROCHE, F),
  std::make_pair(NOIRE + CROCHE, F),
  std::make_pair(CROCHE, F),
  std::make_pair(NOIRE, G2),
  std::make_pair(CROCHE, Dd),
  std::make_pair(NOIRE, G2),
  std::make_pair(NOIRE, Gd),
  std::make_pair(CROCHE, Gd),
  std::make_pair(CROCHE, Gd),
  std::make_pair(CROCHE, G2),
  std::make_pair(CROCHE, G2),
  std::make_pair(CROCHE, F),
  std::make_pair(NOIRE, F),
  std::make_pair(CROCHE, Gd),
  std::make_pair(NOIRE, Ad),
  std::make_pair(CROCHE, Gd),
  std::make_pair(CROCHE, G2),
  std::make_pair(BLANCHE, F),
  std::make_pair(CROCHE, Gd),
  std::make_pair(CROCHE, Gd),
  std::make_pair(CROCHE, G2),
  std::make_pair(CROCHE, G2),
  std::make_pair(CROCHE, F),
  std::make_pair(NOIRE, F),
  std::make_pair(NOIRE, Gd),
  std::make_pair(NOIRE, Dd),
  std::make_pair(NOIRE, Gd),
  std::make_pair(CROCHE, G2),
  std::make_pair(CROCHE, F),
  std::make_pair(CROCHE, G2),
  std::make_pair(CROCHE, Dd),
  std::make_pair(BLANCHE, Gd),
  std::make_pair(NOIRE, Gd),
  std::make_pair(CROCHE, Dd),
  std::make_pair(NOIRE, Dd),
  std::make_pair(NOIRE, C),
  std::make_pair(BLANCHE, Dd)
};

const std::pair<float, float> cascadaBass[cascadaBassSize] = {
  std::make_pair(BLANCHE, 1),
  std::make_pair(CROCHE, 1),
  std::make_pair(CROCHE, Cd1),
  std::make_pair(CROCHE, 1),
  std::make_pair(CROCHE, Cd1),
  std::make_pair(CROCHE, 1),
  std::make_pair(CROCHE, Dd1),
  std::make_pair(CROCHE, 1),
  std::make_pair(CROCHE, Dd1),
  std::make_pair(CROCHE, 1),
  std::make_pair(CROCHE, F0),
  std::make_pair(CROCHE, 1),
  std::make_pair(CROCHE, F0),
  std::make_pair(CROCHE, 1),
  std::make_pair(CROCHE, F0),
  std::make_pair(CROCHE, 1),
  std::make_pair(CROCHE, F0),
  std::make_pair(CROCHE, 1),
  std::make_pair(CROCHE, Cd1),
  std::make_pair(CROCHE, 1),
  std::make_pair(CROCHE, Cd1),
  std::make_pair(CROCHE, 1),
  std::make_pair(CROCHE, Dd1),
  std::make_pair(CROCHE, 1),
  std::make_pair(CROCHE, Dd1),
  std::make_pair(CROCHE, 1),
  std::make_pair(CROCHE, F0),
  std::make_pair(CROCHE, 1),
  std::make_pair(CROCHE, F0),
  std::make_pair(CROCHE, 1),
  std::make_pair(CROCHE, F0),
  std::make_pair(CROCHE, 1),
  std::make_pair(CROCHE, F0),
  std::make_pair(CROCHE, 1),
  std::make_pair(CROCHE, Cd1),
  std::make_pair(CROCHE, 1),
  std::make_pair(CROCHE, Cd1),
  std::make_pair(CROCHE, 1),
  std::make_pair(CROCHE, Gd0),
  std::make_pair(CROCHE, 1),
  std::make_pair(CROCHE, Gd0),
  std::make_pair(CROCHE, 1),
  std::make_pair(CROCHE, Dd1),
  std::make_pair(CROCHE, 1),
  std::make_pair(CROCHE, Dd1),
  std::make_pair(CROCHE, 1),
  std::make_pair(CROCHE, F0),
  std::make_pair(CROCHE, 1),
  std::make_pair(CROCHE, F0),
  std::make_pair(CROCHE, 1),
  std::make_pair(CROCHE, Gd0),
  std::make_pair(CROCHE, 1),
  std::make_pair(CROCHE, Gd0),
  std::make_pair(CROCHE, 1),
  std::make_pair(CROCHE, Gd0),
  std::make_pair(CROCHE, 1),
  std::make_pair(CROCHE, Gd0),
  std::make_pair(CROCHE, 1),
  std::make_pair(CROCHE, Dd1)
};
